AR_LOOP_MODE = {
    NO_LOOP = 0,
    LOOP = 1,
    PING_PONG = 2,
    NO_LOOP_SMOOTH = 3,
}

AR_PLAYBACK_DIRECTION = {
    FORWARD = 1,
    REVERSE = -1,
}

AR_PLAYBACK_TYPE = {
    ABSOLUTE = "absolute",
    RELATIVE = "relative",
}

AR_ANIMATION_STATUS = {
    NOT_STARTED = "NOT_STARTED",
    PLAYING = "PLAYING",
    FINISHED = "FINISHED"
}
AR_FRAME_INTERVAL = 0.02
